### ISSUE TITLE
Overdrawn statement incorrect logic

### ISSUE THREAD

**Issue by ctheinzm** [ctheinzm/ser316labcr#8]
Category: FD
Savings.java
39

My issue #6 and Haocheng's issue #10 are that the overdrawn if statement currently reads "if balance is 0 or less (balance <=0.0f), change account to overdrawn"
when it should be "if balance is less than zero (balance < 0.0f), chance account to overdrawn

**Comment by hzhan147** [comment]
Fixed and merged into master.
